using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace WhiteLagoon.Domain.Entities
{
    public class VillaNumber
    {

        [Key,DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name ="Villa Number")]
        //DatabaseGeneratedOption.None explicitly
        //indicates that the database should not generate values for this property.
        //In other words, the values for the Villa_Number property will not be automatically
        //generated by the database, and they are expected to be provided explicitly when inserting data.
        public int Villa_Number{ get; set; }

        [ForeignKey("Villa")]
        [Display(Name ="Villa Name")]
        public int VillaId { get; set; }


        //The[NotMapped] attribute is used to specify that a property should not be included
        //in the database schema.It tells EF Core to ignore the property when creating or
        //updating the database.


        [ValidateNever]
        //The[ValidateNever] attribute is used specifically in the context of input
        //model validation during model binding in ASP.NET Core applications.
        public Villa Villa { get; set; }

        public string? SpecialDetails { get; set; }

    }
}
